# Generated by Django 4.1 on 2022-08-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wardrobe',
            name='headline',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='wardrobe',
            name='clothing',
            field=models.ImageField(blank=True, default='defalt.png', null=True, upload_to='images'),
        ),
    ]
