# Generated by Django 4.1 on 2022-08-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_wardrobe_headline_alter_wardrobe_clothing'),
    ]

    operations = [
        migrations.AddField(
            model_name='wardrobe',
            name='colour',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='wardrobe',
            name='headline',
            field=models.CharField(max_length=200),
        ),
    ]
