# Generated by Django 4.1 on 2022-08-20 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_wardrobe_colour_alter_wardrobe_headline'),
    ]

    operations = [
        migrations.AddField(
            model_name='wardrobe',
            name='article',
            field=models.CharField(default='pants', max_length=100),
        ),
    ]
