# Generated by Django 4.1 on 2022-08-21 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_wardrobe_headline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wardrobe',
            name='headline',
        ),
    ]
